### ISSUE TITLE
EK UI gen and 64bit dll

### ISSUE THREAD

**Issue by timesscar** [EmptyKeys/UI_Framework#10]
I am attempting to make an xbox frontend app for my game project, which requires 64 bit.  I switched everything over, but ekuigen.exe no longer can load them, so I suspect that means ekuigen is 32 bit.   I can build it myself 64 bit or do some project juggling, but it would simpler if ekuigen included a 64 bit version in the nuget package.  Would that feasible?

**Comment by EmptyKeys** [comment]
Hi, not sure why you need it. Ekuigen executable is used only during compile time so not needed to publish that with the game.

**Comment by timesscar** [comment]
Right, one of the dlls is used in my game (thus requires 64 bit) and ekuigen also needs to reference it for certain types.

**Comment by EmptyKeys** [comment]
which one?

**Comment by timesscar** [comment]
Sorry, I'm not being clear.... ekuigen needs to load my assemblies in order to generate the .cs files.  they are x64 so ekuigen can't load them.  I can change their target temporarily to x86 then build the .cs files, its just a bit of a pain.  A 64bit build in the same tools directory would make life easier, like ekuigen64.exe or something.

**Comment by EmptyKeys** [comment]
I see. Well generator is open source so you can try to switch it to 64bit - https://github.com/EmptyKeys/UI_Generator
