### ISSUE TITLE
Disable gamepad capture

### ISSUE THREAD

**Issue by timesscar** [EmptyKeys/UI_Framework#11]
I need to switch focus between the UI other game components and I can't seem to figure out a way to enable/disable gamepad capture.  Is there a way?
EDIT:  to be clear I am specifically looking for a way to make the UI elements ignore the gamepad.

**Comment by EmptyKeys** [comment]
There is not feature like this in the UI, but you could change engine specific library to ignore game pad. Code is [here](https://github.com/EmptyKeys/UI_Engines)

**Comment by timesscar** [comment]
I created PR https://github.com/EmptyKeys/UI_Engines/pull/17 which adds a flag to enable/disable gamepad capture.

**Comment by EmptyKeys** [comment]
thanks, i will add that with the next version

**Comment by EmptyKeys** [comment]
merge done
