### ISSUE TITLE
KeyUp event on TextBox

### ISSUE THREAD

**Issue by Wompuz** [EmptyKeys/UI_Framework#12]
Is it possible to handle a KeyUp or KeyDown event on a TextBox? I can't find an example and if I try to bind a KeyEventHandler I get the following error:

`#error 'Provide value on 'System.Windows.Data.Binding' threw an exception.' Line number '1' and line position '2066'.`

**Comment by EmptyKeys** [comment]
You can do that with EventTriggerBehavior in XAML so for example ...

`<TextBox Name="searchInput" Grid.Column="1" Grid.Row="3" Text="{Binding SearchString}" Margin="2,0,2,2">
<TextBox.InputBindings>
                        <KeyBinding Key="Enter" Command="{Binding SearchCommand}" />
                    </TextBox.InputBindings>
                    <eki:Interaction.Behaviors>
                        <eki:EventTriggerBehavior EventName="PreviewKeyUp">
                            <eki:EventTriggerBehavior.Actions>
                                <eki:InvokeCommandAction Command="{Binding SearchCommand}" />
                            </eki:EventTriggerBehavior.Actions>
                        </eki:EventTriggerBehavior>
                    </eki:Interaction.Behaviors>
                </TextBox>`

This TextBox will bind Enter key and any press of any key to Search Command.

You have to use namespace
xmlns:eki="clr-namespace:EmptyKeys.UserInterface.Designer.Interactions;assembly=EmptyKeys.UserInterface.Designer"
