### ISSUE TITLE
Open sourcing 

### ISSUE THREAD

**Issue by val-andrushko** [EmptyKeys/UI_Framework#13]
Will EK ever be open source? It seems rather abandoned right now and I do not dare to use something what is not fully open source and seems abandoned at the same time. I've encountered a weird bug with the generator which I didn't even submit because when I looked at current issues, this seems like an abandoned project. It is also a shame that it is impossible to properly extend stuff : /

**Comment by EmptyKeys** [comment]
There are two parts of EK UI, which are open source:

https://github.com/EmptyKeys/UI_Engines
https://github.com/EmptyKeys/UI_Generator

Those are open source so you can extend the UI with what ever feature you want. The rest of the library is not open source and it's not planned to be one.

The last update was 4 months ago, so it's not abandoned, actually there are some fixes/changes/new features already done for the next version.

If you have any bug for UI Generator, pls report it in UI Generator project and I will check it out.
