### ISSUE TITLE
Binding ItemsSource

### ISSUE THREAD

**Issue by nerdkl** [EmptyKeys/UI_Framework#18]
do i have to use arrays in my bindings at itemssource ? 
im using an IEnumerable... but its tryn to use an index on it, l ike on an array?

    [GeneratedCodeAttribute("Empty Keys UI Generator", "3.2.0.0")]
    public class MouseSelectorViewModel_Definitions_PropertyInfo : IPropertyInfo {
        
        public System.Type PropertyType {
            get {
                return typeof(System.Collections.Generic.IEnumerable<OldDeus.Core.BlockDefinition>);
            }
        }
        
        public bool IsResolved {
            get {
                return true;
            }
        }
        
        public object GetValue(object obj) {
            return ((OldDeus.Base.ViewModel.MouseSelectorViewModel)(obj)).Definitions;
        }
        
        public object GetValue(object obj, object[] index) {
            return ((OldDeus.Base.ViewModel.MouseSelectorViewModel)(obj)).Definitions[((int)(index[0]))];
        }
        
        public void SetValue(object obj, object value) {
        }
        
        public void SetValue(object obj, object value, object[] index) {
        }
    }

**Comment by EmptyKeys** [comment]
Hi, ItemsSource needs collection.
