### ISSUE TITLE
KeyBinding as InputBinding not working without Focus on Control

### ISSUE THREAD

**Issue by nerdkl** [EmptyKeys/UI_Framework#19]
do it has to be like that?
same for KeyDown events etc. ...
Is it possible to change that ?

wrong topic but what do u think about unhandled mouseclick event on UIRoot. u have already unhandled MouseDoubleClick on it!?

**Comment by EmptyKeys** [comment]
Hi, library is based on features of WPF and this is standard behaviour.

**Comment by nerdkl** [comment]
but it would be so nice. for example if i use standart way to move on my terrain, with Monogame Keyboardstate and i focus at same time a textbox. I wont to move i wont to type :) etc... 
how to auto focus first control automatically

**Comment by nerdkl** [comment]
actually if i have an wpf window without controls its fireing the event!
can u make the UIRoot focusable? i tried to focus it but no luck :D
