### ISSUE TITLE
Am I stupid or is there something really wrong, Grid

### ISSUE THREAD

**Issue by nerdkl** [EmptyKeys/UI_Framework#23]
<Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto"/>
            <ColumnDefinition Width="*"/>
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>
        <Grid  Grid.Column="0" Grid.Row="0" Grid.ColumnSpan="2">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="Auto"/>
                <ColumnDefinition Width="*"/>
            </Grid.ColumnDefinitions>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto"/>
                <RowDefinition Height="*"/>
                <RowDefinition Height="Auto"/>
                <RowDefinition Height="*"/>
            </Grid.RowDefinitions>
            <Button Content="Menu" Command="{Binding MenuCommand}"/>
            <TextBlock Grid.Column="1" Text="Legacy of Old Deus development" Margin="10, 0, 0, 0"/>
            <StackPanel Grid.Row="2">
                <Button Content="Add" Command="{Binding AddBlockCommand}"/>
                <Button Content="Remove" Command="{Binding RemoveBlockCommand}"/>
            </StackPanel>
            <Border Grid.Column="1" Grid.Row="1" Grid.RowSpan="3" Margin="10, 10, 10, 10" BorderBrush="Black" BorderThickness="2">
                <TextBlock Text="hud display"/>
            </Border>
        </Grid>
        <Border Grid.Column="0" Grid.Row="2" Width="300" Height="300" HorizontalAlignment="Left" BorderBrush="Black" BorderThickness="2">
            <TextBlock Text="Minimap"/>
        </Border>
    </Grid>

bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   bei EmptyKeys.UserInterface.DefinitionCollection`1.get_Item(Int32 index)
   bei EmptyKeys.UserInterface.Controls.Grid./*ۛ()
   bei EmptyKeys.UserInterface.Controls.Grid.MeasureOverride(Size availableSize)
   bei EmptyKeys.UserInterface.UIElement./*ȗ(Size 00218*/)
   bei EmptyKeys.UserInterface.UIElement.Measure(Size availableSize)
   bei EmptyKeys.UserInterface.Controls.ContentPresenter.MeasureOverride(Size availableSize)
   bei EmptyKeys.UserInterface.UIElement./*ȗ(Size 00218*/)
   bei EmptyKeys.UserInterface.UIElement.Measure(Size availableSize)
   bei EmptyKeys.UserInterface.Controls.Border.MeasureOverride(Size availableSize)
   bei EmptyKeys.UserInterface.UIElement./*ȗ(Size 00218*/)
   bei EmptyKeys.UserInterface.UIElement.Measure(Size availableSize)
   bei EmptyKeys.UserInterface.Controls.Control.MeasureOverride(Size availableSize)
   bei EmptyKeys.UserInterface.UIElement./*ȗ(Size 00218*/)
   bei EmptyKeys.UserInterface.UIElement.Measure(Size availableSize)
   bei EmptyKeys.UserInterface.Controls.UIRoot.UpdateLayout(Double elapsedGameTime)
   bei LegacyOfOldDeus.Components.HudComponent.Update(GameTime gameTime) in C:\Users\klaus\source\repos\LegacyOfOldDeus\LegacyOfOldDeus\Components\HudComponent.cs:Zeile 41.
   bei Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   bei LegacyOfOldDeus.LOODGame.Update(GameTime gameTime) in C:\Users\klaus\source\repos\LegacyOfOldDeus\LegacyOfOldDeus\LOODGame.cs:Zeile 87.
   bei Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   bei Microsoft.Xna.Framework.Game.Tick()
   bei Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   bei Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   bei LegacyOfOldDeus.Program.Main() in C:\Users\klaus\source\repos\LegacyOfOldDeus\LegacyOfOldDeus\Program.cs:Zeile 17.

**Comment by nerdkl** [comment]
your ui dont like nested things. see https://github.com/EmptyKeys/UI_Framework/issues/17

**Comment by EmptyKeys** [comment]
<Border Grid.Column="0" Grid.Row="2" Width="300" Height="300" HorizontalAlignment="Left" BorderBrush="Black" BorderThickness="2">
        <TextBlock Text="Minimap"/>
    </Border>

this is wrong, Index of rows starts from 0.

**Comment by nerdkl** [comment]
so and where do i use negative values ? XD

**Comment by nerdkl** [comment]
i found my error 

    <Border Grid.Column="0" Grid.Row="2" Width="300" Height="300" HorizontalAlignment="Left" BorderBrush="Black" BorderThickness="2">
        <TextBlock Text="Minimap"/>
    </Border>

row was 2 but actually max row index is 1 this should not happen :D
