### ISSUE TITLE
How to stretch combobox inside itemscontrol

### ISSUE THREAD

**Issue by nerdkl** [EmptyKeys/UI_Framework#26]
![itemscontrol](https://user-images.githubusercontent.com/12494009/76010889-e9d09600-5f13-11ea-8502-655993edc1bc.PNG)

    <ScrollViewer  Grid.Row="1" Grid.Column="1">
        <ItemsControl ItemsSource="{Binding SelectedBuilding.BuildingSlots}" HorizontalContentAlignment="Stretch">
            <ItemsControl.ItemTemplate>
                <DataTemplate DataType="{x:Type view:BuildingSlotsWrapper}">
                    <ComboBox ItemsSource="{Binding Slots}" SelectedItem="{Binding SelectedSlot}" SelectedIndex="{Binding SelectedSlotIndex}" HorizontalAlignment="Stretch">
                        <ComboBox.ItemTemplate>
                            <DataTemplate DataType="{x:Type core:BuildingSlot}">
                                <TextBlock Text="{Binding Name}" VerticalAlignment="Center"/>
                            </DataTemplate>
                        </ComboBox.ItemTemplate>
                    </ComboBox>
                </DataTemplate>
            </ItemsControl.ItemTemplate>
        </ItemsControl>
    </ScrollViewer>

**Comment by EmptyKeys** [comment]
try ContentHorizontalAlignment or make your own style for ComboBox
