### ISSUE TITLE
.net standard support

### ISSUE THREAD

**Issue by timesscar** [EmptyKeys/UI_Framework#3]
Do you have any plans for moving from PCL to .net standard?  I've been able to migrate all my components to .net standard libraries except the ones that directly deal with the UI.

**Comment by EmptyKeys** [comment]
yes, i have .net standard 2.0 version ready, just finishing one feature before release

**Comment by timesscar** [comment]
Awesome, I'm excited to try it!  Need a beta tester?  :)

**Comment by EmptyKeys** [comment]
Not at this moment. It's already part of my game on Steam. But thanks :)

**Comment by timesscar** [comment]
Cool, picked up a copy.  Thanks for your work!

**Comment by Wompuz** [comment]
Can't wait for the .net standard release! 👍

**Comment by devedse** [comment]
Yeah I'm currently working on a game, but I think I'll wait a few days before starting with Empty Keys as I don't want to start on the old version when a new one is just around the corner :smile:

**Comment by EmptyKeys** [comment]
And so 3.1 version is out. Let me know if you have any issue

**Comment by Wompuz** [comment]
I only had to upgrade the .NET framework of the UserInterface project to 4.7.2 (it was 4.6.1) but after that no problems. Worked great with all projects for different platforms.

**Comment by timesscar** [comment]
Looks great!
