### ISSUE TITLE
Updates for .net standard 2.1 (and subsequently MonoGame 3.8)

### ISSUE THREAD

**Issue by timesscar** [EmptyKeys/UI_Framework#30]
Currently the .net standard targeted by EmptyKey is 2.0, which does not support .net core 3.1.  An update to the nugets with this support would be appreciated.

**Comment by EmptyKeys** [comment]
Hi,
you can still use .net standard 2.0 with .net core 3.1. for now.
I will release new version of library (3.3) for new MonoGame.
