### ISSUE TITLE
Corner Radius Not supported

### ISSUE THREAD

**Issue by ghost** [EmptyKeys/UI_Framework#31]
Borders work but can't have rounded corners.
If a border is given the property CornerRadius; it is ignored by the generator.
If built with a Style with a property, CornerRadius, the generator creates an error.

Can this be support? I see _Rectangles_ with round corners, why not _Borders_? 

```
<Style x:Key="gridBorder" TargetType="{x:Type Border}">
  <Setter Property="CornerRadius" Value="3" />
</Style>
```
> #error Type CornerRadius not supported
> Setter r_2_s_S_4 = new Setter(Border.CornerRadiusProperty, "NOT SUPPORTED!");

**Comment by EmptyKeys** [comment]
Use Rectangle instead.
