### ISSUE TITLE
Has work on this UI framework stopped? I'm worried to use it...

### ISSUE THREAD

**Issue by Thraka** [EmptyKeys/UI_Framework#32]
While it seems one of the best UI frameworks for MonoGame, I mean reimplementing XAML is awesome, I'm worried that it's going to fall into an unsupported category. The tools and libraries seem to have been dormant since 2020. So many changes have come into the .NET eco system, such as .NET Global tooling, new project file formats, and new .NET versions (Core 3.1 is out of support starting December and .NET Framework 4.6.1 ended in April of this year), who is going to update these things? 

For example, if a new version of MonoGame comes out and something down that dependency chain for the core library breaks, are we out of luck? If the current maintainer gets into a car accident and dies, how would we get the source code so that we can update the library?

I would love to use this library, but it seems it's not active anymore. :( I would love to go through and update all these projects to the new formats and target modern frameworks, updating the tooling, and more, but I feel like I would just be doing 75% of the upgrades without being able to upgrade the base framework UI because it isn't open source :(

**Comment by EmptyKeys** [comment]
Hi,
This library is still active and used on my projects and I update it when it's needed. Part of it is open source just in case when someone needs changes to engine specific code.

https://github.com/EmptyKeys/UI_Engines

So if you need some update to that part of the code you can let me know or do it yourself.

Generator is also open source, if you need some new control.

https://github.com/EmptyKeys/UI_Generator

The rest of the UI (controls etc.) is modular enough similarly to WPF so you can do alot without any kind of changes in source code unless there is some bug. Feel free to report those.

Thanks
