### ISSUE TITLE
How do you use events?

### ISSUE THREAD

**Issue by Thraka** [EmptyKeys/UI_Framework#34]
I can't seem to add events to the XAML, as the generator complains with errors such as:

```
 System.ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
```

I'm just creating a grid and trying to add the Loaded event in the XAML.

**Comment by EmptyKeys** [comment]
Hi,
whole framework is build around MVVM design pattern, similar to what would you use in WPF. Don't use code behind and you should be fine.
