### ISSUE TITLE
UI scaling

### ISSUE THREAD

**Issue by Wompuz** [EmptyKeys/UI_Framework#4]
I see that you have used UI scale in your game Children of the Galaxy (https://twitter.com/CotGGame/status/830535128803860481). I can't find anything on how to do this with EmptyKeys, can anyone explain to me how I can use UI Scaling?

**Comment by EmptyKeys** [comment]
Hi, there are UIRoot.DpiX [http://emptykeys.com/EmptyKeysUI/html/P_EmptyKeys_UserInterface_Controls_UIRoot_DpiX.htm](url) and UIRoot.DpiY static properties. By default it's 96 DPI. You can change that number. Just remember if you are using some pictures or bitmap fonts, you will have to provider higher resolution of those.

I do it in my game by making all UI pictures bit bigger even for 96 DPI and when i scale them it still looks ok. Bitmap fonts are bit harder. I have 3 sets of fonts with different size for each DPI setting and based on DPI i load specific set.

**Comment by Wompuz** [comment]
That works great, thanks! I still have to figure out the fonts but the rest works as a charm 👍
