### ISSUE TITLE
DataContext with Anonymous Type

### ISSUE THREAD

**Issue by Wompuz** [EmptyKeys/UI_Framework#7]
When I'm using a DataContext with Anonymous Type like so

`DataContext = new { login = BuildLoginUIModel(), options = BuildOptionsUIModel() }`

The bindings in the UI don't get updated. The PropertyChanged event seems to be called but it doesn't update the property in the UI. Also ICommands that are set on buttons don't work. I've also tried to apply this in the sample by setting this in the Game1.cs file:

`basicUI.DataContext = new { test1 = viewModel };`

And appending the test1 at all bindings like so:

```
<Button Name="button1" Grid.Row="0" Grid.Column="1" Content="Button 1" Width="200" Height="30" Margin="5" HorizontalAlignment="Left"
                            Command="{Binding test1.ButtonCommand}" CommandParameter="Click Button 1" TabIndex="1">
```

And it seems to break all bindings. Is anonymous type with DataContext supported?

**Comment by Wompuz** [comment]
I've looked into it a little bit and I think that when creating the Binding like so

`Binding binding_cancelOptionsButton_Command = new Binding("options.ButtonCommandCancel");`

It can't locate the right property and it drops back to the FallbackValue property in the Binding class.

**Comment by Wompuz** [comment]
It seems to work with Uppercase like so:

`DataContext = new { Login = BuildLoginUIModel(), Options = BuildOptionsUIModel() }`

But the properties now don't update in the UI when changed.

**Comment by EmptyKeys** [comment]
Hmm i never tried that and i would not recommend it. Having specific class (and type) for View Model is better. You can avoid using reflection in UI and you can test it properly.

**Comment by Wompuz** [comment]
I solved this by including a property for the OptionsUIViewModel (for the UserControl) in my LoginUIViewModel and setting it in the constructor. I will just do this for every View I use the OptionsUI UserControl in:

```
public OptionsUIViewModel Options { get; set; }

public LoginUIViewModel(OptionsUIViewModel optionsUIViewModel)
{
        Options = optionsUIViewModel;
}
```
and used bindings as such:

`<CheckBox Name="fullScreenCheckbox" IsChecked="{Binding Options.FullScreen}"  Grid.Row="1" Grid.Column="1" Width="200" Margin="5" HorizontalAlignment="Left"  TabIndex="1" />`
